### ISSUE TITLE
VEGUI may not be working with the latest version of R

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#127]
VEGUI is working in R 3.3.2.  However, in R 3.4.1 , VEGUI starts up but issues a series of warnings, and then fails to populate the directory tree when the user clicks Select Scenario Script.

```
Warning in file.info(files) :
  cannot open file 'C:/hiberfil.sys': The process cannot access the file because it is being used by another process
Warning in file.info(files) :
  cannot open file 'C:/MSOCache': Access is denied
Warning in file.info(files) :
  cannot open file 'C:/pagefile.sys': The process cannot access the file because it is being used by another process
Warning in file.info(files) :
  cannot open file 'C:/PerfLogs': Access is denied
Warning in file.info(files) :
  cannot open file 'C:/swapfile.sys': The process cannot access the file because it is being used by another process
Warning in file.info(files) :
  cannot open file 'C:/System Volume Information': Access is denied
```

Running `sessionInfo()` under R 3.4.1 reveals that a few packages, especially shiny related ones, were updated,  with respect to R 3.3.2.  We suspect we need to make a small change to the GUI for one of the package updates.

**Comment by goreaditya** [comment]
The R v3.4.1 has a different way of implementing `file.info()` compared to R v3.3.2. The reason for these warnings are the calls made to `file.info` by `shinyFiles` methods. One way to resolve this issue is to override the `file.info()` and a base method from the package `shinyFiles` called `fileGetter` by custom functions. This resolves the problem but it might not be a good solution for long term. Any suggestions?

**Comment by bstabler** [comment]
Unfortunately it appears this issue is low priority for the [shinyFiles](https://github.com/thomasp85/shinyFiles/issues/57) project.

**Comment by jrawbits** [comment]
It is worth wondering why this issue is a low priority for shinyFiles project:  are you doing something that is not officially supported in the package, or using something in a way that is not intended?  I don’t necessarily want to get a response to that question myself, but it seems like a workaround will be required, and exploring answers to that question will be one way you might find the workaround.

Best, Jeremy
