### ISSUE TITLE
convert RPAT urban module to VELandUse module

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#136]
create RPAT placetypes as VE bzones (with one overall azone)

**Comment by bstabler** [comment]
The CalculatePlaceTypes module will be added to the VELandUse package

**Comment by bstabler** [comment]
@goreaditya is going to check that the number of hhs and employees by place type are similar to what RPAT had before.

**Comment by goreaditya** [comment]
@bstabler I checked and the Hh numbers are different because the VESimHousholds package uses a different Income model and also uses additional attributes called group quarters that I cannot set to 0.
For the employees by place type the numbers are different because the order in which the random numbers are generated for place types. It was more hard coded in RPAT compared to the placetype modules in VELandUse.

**Comment by goreaditya** [comment]
# Comparison between RPAT and VERPAT outputs
=============================================
--------------------------------
## Comparison of households
--------------------------------
### Total Population
Input: 692826

RPAT: 692838

VERPAT: 692865

The difference observed in the value is because the probability distribution by HHtype is different.
VESimHouseholds uses an estimation model to calculate the distribution values.

### Population distribution by age
Input:

| Age0to14 | Age15to19 | Age20to29 | Age30to54 | Age55to64 | Age65Plus |
|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|
| 129869 | 41133 | 99664 | 277854 | 71658 | 72648 | 
 
 
RPAT:

| Age0to14 | Age15to19 | Age20to29 | Age30to54 | Age55to64 | Age65Plus |
|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|
| 129981 | 41136 | 99647 | 277757 | 71662 | 72655 | 

VERPAT:

| Age0to14 | Age15to19 | Age20to29 | Age30to54 | Age55to64 | Age65Plus |
|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|
| 130024 | 41148 | 99643 | 277730 | 71662 | 72658 |

### Distribution within age groups

RPAT:

|   group   |   0    |   1   |   2   |  3   |  4   |
|:---------:|:------:|:-----:|:-----:|:----:|:----:|
| Age0to14  | 227274 | 31576 | 26377 | 9617 | 4200 |
| Age15to19 | 265427 | 26098 | 7519  |  0   |  0   |
| Age20to29 | 226596 | 45249 | 27199 |  0   |  0   |
| Age30to54 | 114644 | 91043 | 93357 |  0   |  0   |
| Age55to64 | 244177 | 38072 | 16795 |  0   |  0   |
| Age65Plus | 244244 | 36945 | 17855 |  0   |  0   |

VERPAT:

|   group   |   0    |   1   |   2   |  3   |  4   |  5  |  6  | 7  | 8  |
|:---------:|:------:|:-----:|:-----:|:----:|:----:|:---:|:---:|:--:|:--:|
| Age0to14  | 219543 | 32767 | 27299 | 9522 | 2564 | 542 | 129 | 23 | 24 |
| Age15to19 | 259342 | 25868 | 6393  | 746  |  64  |  0  |  0  | 0  | 0  |
| Age20to29 | 223344 | 42574 | 23315 | 2505 | 500  | 126 | 49  | 0  | 0  |
| Age30to54 | 110877 | 88106 | 90976 | 2190 | 218  | 46  |  0  | 0  | 0  |
| Age55to64 | 237563 | 38114 | 16660 |  76  |  0   |  0  |  0  | 0  | 0  |
| Age65Plus | 238439 | 35554 | 18169 | 238  |  13  |  0  |  0  | 0  | 0  |

### Distribution by household size

RPAT:

| HHsize |   1   |   2    |   3   |   4   |   5   |  6   |  7   |  8  |  9  | 10 | 11 |
|--|:-----:|:------:|:-----:|:-----:|:-----:|:----:|:----:|:---:|:---:|:--:|:--:|
| Household | 90155 | 114046 | 39587 | 32686 | 14159 | 5865 | 1636 | 618 | 219 | 69 | 4  |

VERPAT:

| HHsize |   1   |   2    |   3   |   4   |   5   |  6   |  7   |  8  |  9  | 10 |
|--|:-----:|:------:|:-----:|:-----:|:-----:|:----:|:----:|:---:|:---:|:--:|
| Household | 80361 | 112616 | 42915 | 34494 | 14610 | 5297 | 1461 | 488 | 122 | 49 |

### Distribution by drivers

RPAT:

| Drv1  |  Drv2  | Drv3Plus |
|:-----:|:------:|:--------:|
| 98779 | 154373 |  45892   |

VERPAT:

| Drv1  |  Drv2  | Drv3Plus |
|:-----:|:------:|:--------:|
| 89101 | 154006 |  49306   |

### Total Income

RPAT: $14,908,924,046
VERPAT: $22,531,543,724

This difference is observed due to difference in households and the income model used.

### Distribution by place types

RPAT:

| CIC M | CIC R |  Rur  | Sub M | Sub R | UC MU | UC R  | UC T  |
|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 32384 | 48425 | 13280 | 29500 | 88631 | 28792 | 29017 | 29015 |

VERPAT:

| CIC_M | CIC_R |  Rur  | Sub_M | Sub_R | UC_M  | UC_R  | UC_T  |
|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 29547 | 44103 | 13294 | 27815 | 83394 | 31344 | 31447 | 31469 |

--------------------------------
## Comparison of Businesses
--------------------------------

These differences are mainly observed due to the difference in the order
of random number generation

### Total number of businesses

RPAT: 1992102
VERPAT: 1992102

### Total number of employees

RPAT: 459578
VERPAT: 459578

### Distribution by place types

RPAT:

| CIC E | CIC M | Rur  | Sub E | Sub M | UC E | UC MU | UC T |
|:-----:|:-----:|:----:|:-----:|:-----:|:----:|:-----:|:----:|
| 4979  | 2416  | 2525 | 4950  | 2451  | 2405 | 2467  | 2409 |

VERPAT:

| CIC_E | CIC_M | Rur  | Sub_E | Sub_M | UC_E | UC_M | UC_T |
|:-----:|:-----:|:----:|:-----:|:-----:|:----:|:----:|:----:|
| 4979  | 2467  | 2416 | 4950  | 2525  | 2405 | 2409 | 2451 |

### Distribution of employees by place types

RPAT:

| CIC E  | CIC M |  Rur  | Sub E | Sub M | UC E  | UC MU | UC T  |
|:------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 100679 | 45336 | 61843 | 75112 | 44375 | 43079 | 40463 | 48691 |

VERPAT:

| CIC_E  | CIC_M |  Rur  | Sub_E | Sub_M | UC_E  | UC_M  | UC_T  |
|:------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 100679 | 40463 | 45336 | 75112 | 61843 | 43079 | 48691 | 44375 |

### Distribution of firms by place types

RPAT:

| CIC E  | CIC M  |  Rur   | Sub E  | Sub M  |  UC E  | UC MU  |  UC T  |
|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| 507653 | 182021 | 171939 | 325945 | 168458 | 187576 | 240951 | 207559 |

VERPAT:

| CIC_E  | CIC_M  |  Rur   | Sub_E  | Sub_M  |  UC_E  |  UC_M  |  UC_T  |
|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| 507653 | 240951 | 182021 | 325945 | 171939 | 187576 | 207559 | 168458 |

**Comment by goreaditya** [comment]
@bstabler I have shown the comparison of the RPAT and VERPAT outputs in the tables above.

**Comment by bstabler** [comment]
This looks good enough to move on to the next task.  Thanks!
