### ISSUE TITLE
testModule fails if get specifications contain only global or baseyear group

### ISSUE THREAD

**Issue by goreaditya** [gregorbj/VisionEval#148]
The command;
```
testModule(ModuleName = "XYZ", LoadDatastore = TRUE, SaveDatastore = TRUE,
  DoRun = FALSE)
```
breaks if the `Get` specifications of the module `XYZ` only contain variables from `"Global"` or `"BaseYear"` group. I believe the failure happens at line `779`:

`L <- getFromDatastore(Specs_ls, RunYear = Year, Geo = NULL)`

as the `Year` variable is not created beforehand. This happens only for a specific case where:
1. The module's `Get` specifications only contain `"Global"` or `"BaseYear"` group variables, and
2. The `DoRun` option is set to `FALSE`.

**Comment by gregorbj** [comment]
Two things caused the error which only occurred when DoRun is FALSE and no Get items have GROUP attribute value of "Year". As identified above, under these circumstances, there is no object named Year. When DoRun is TRUE, Year is created in a for loop that iterates through RunYears, assigning a value to Year in each iteration. When DoRun is FALSE, Year is not created. However, if any of the Get items have a GROUP attribute value of "Year", the code that checks whether the datastore contains all data specified by Get items uses a loop to check whether the items are in each year group. This is done by iterating with a for loop which assigns a value to Year in each iteration. The problem was solved by assigning a value to Year when DoRun is FALSE.

**Comment by bstabler** [comment]
Looks the like build didn't pass?  https://travis-ci.org/gregorbj/VisionEval/builds/336719001?utm_source=github_status&utm_medium=notification

**Comment by gregorbj** [comment]
Appears to be a problem with VESimHouseholds. That package is not building and every package that depends on it fails because VESimHouseholds fails. When I run devtools::document() locally, I get the following error.

Saving AssignLifeCycleSpecifications as AssignLifeCycleSpecifications.rda to C:\Users\Brian\Documents\GitHub\VisionEval\sources\modules\VESimHouseholds/data
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'an integer', got '"0000045"'
Called from: scan(file = file, what = what, sep = sep, quote = quote, dec = dec, 
    nmax = nrows, skip = 0, na.strings = na.strings, quiet = TRUE, 
    fill = fill, strip.white = strip.white, blank.lines.skip = blank.lines.skip, 
    multi.line = FALSE, comment.char = comment.char, allowEscapes = allowEscapes, 
    flush = flush, encoding = encoding, skipNul = skipNul)

When I attempt to build I get a similar error:
Saving AssignLifeCycleSpecifications as AssignLifeCycleSpecifications.rda to C:\Users\Brian\Documents\GitHub\VisionEval\sources\modules\VESimHouseholds/data
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'an integer', got '"0000045"'
Error : unable to load R code in package 'VESimHouseholds'
ERROR: lazy loading failed for package 'VESimHouseholds'
* removing 'C:/Users/Brian/Documents/R/win-library/3.4/VESimHouseholds'
* restoring previous 'C:/Users/Brian/Documents/R/win-library/3.4/VESimHouseholds'

Exited with status 1.

So the error has something to do with the AssignLifeCycleSpecifications.rda. Not obvious what the problem is and I don't remember making any changes in the last commit.

**Comment by gregorbj** [comment]
Found the problem. Has nothing to do with AssignLifeCycleSpecifications. Had changed the processEstimationInputs function in visioneval so that the classes of data that is read is is consistent with the specifications of the data using the colClasses argument. However some of the data in the fields of the pums_households.csv and pums_persons.csv files were not consistent with the specifications (e.g. SERIALNO is text rather than a number. This was not a problem before because read.csv would convert the data behind the scenes. Fixed the problem by modifying specs to be consistent with the data.

**Comment by gregorbj** [comment]
Build passed
