### ISSUE TITLE
add passing of globals/modelstate within the list

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#24]
add passing of globals/modelstate within the list, so that modules can access/set variables across different parts of the code.  Long term, potentially turn off the ability to use globals in the local functions.

**Comment by gregorbj** [comment]
I need an example use case to understand the need better. I think that the approaches to issues #30 and #31 might address the need but am not sure.

**Comment by bstabler** [comment]
Take a look at the current pilot properties file for VE RPAT - https://github.com/RSGInc/VisionEvalRPAT/blob/master/defs/parameters.json

**Comment by gregorbj** [comment]
OK. The model run parameters are stored in the "ModelState.Rda" file. The "getModelState" function reads the contents of that file. I think there are 2 choices for how to make values in that file accessible to a module.
1) Have the "runModule" function read the contents and pass them as a component of the list that is passed to the module. We'd need to have a convention for the name of this component. For example, in the VisionEval functions that use the contents, this is assigned to "G". So for example to get the "RunTypes" parameter for RPAT. the module would refer to G$RunTypes.
2) Export the "getModelState" function so that module code can access the desired parameter from the "ModelState.Rda" file. The function is written so that you can just read the desired parameter. For example getModelState("RunTypes").
I'm thinking we should do the first. What do you think?
Also, the "EmploymentGrowth" parameter in the example should be put in the new "model_parameters.json" file whose contents get loaded into the "Global/Model" table of the datastore. The value should be accessed using a Get specification. The "model_parameters.json" contains model parameters that are not specific to a module. The "run_parameters.json" file contains parameters related to the definition and control of a model run.

**Comment by gregorbj** [comment]
A variant has been implemented in the latest development version. The "VisionEvalRPAT" repo shows an example of how this approach is used in with the "VisionEvalSyntheticFirms" package. There are two modules in that package "CreateBaseSyntheticFirms" and "CreateFutureSyntheticFirms". The procedures are  different and the future procedure uses data produced by the base procedure. The specifications for each procedure are very different. Therefore it makes sense that they should be different modules. The model run code determines which procedure should run based on the Year.
