### ISSUE TITLE
 lost the concise formatting of our original VisionEval github website

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#58]
@mrspeel 

We seem to have lost the concise formatting of our original VisionEval github website (https://gregorbj.github.io/VisionEval/). We used to have a nice abbreviated “topics” list where you could click on a topic to open it for more information.

**Comment by gregorbj** [comment]
When local copy the webpage (index.html) is opened, the page shows properly. For some reason when the index.html in the GitHub repository is opened, the bootstrap library is not being loaded. I don't know why.

**Comment by gregorbj** [comment]
I wonder whether we need to delete the gh-pages branch and republish. I get the impression from the following article that publishing a website involves a build process. Perhaps if it isn't built properly then libraries specified in link and script tags are not properly loaded.

**Comment by gregorbj** [comment]
Confirmed that the problem is that the link and script tags for loading the bootstrap css and js files referred to http rather than https. Editing the script has not solved the problem since the github.io webpage does not show the edits. I think we may need to delete the gh-pages branch and recreate it in order to solve the problem.

**Comment by gregorbj** [comment]
It works now. It may be that GitHub just needs a bit of time to update their server with the edited webpage.
