### ISSUE TITLE
If and how to handle measurement units

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#6]
At a minimum, it is important that modules document the measurement units of the outputs they produce (e.g. is the estimate of CO2e measured in pounds, grams, metric tons?). Module developers and model users need to know these units in order to make correct calculations using the outputs. This should be made clear in the documentation for the module. In addition, the measurement units of a dataset can be stored as an attribute of the dataset in the HDF5 file. Moreover, if the names of units are standardized, then module developers can write their modules to convert between units as needed. For example if the data store has fuel consumption in gallons and a module needs it in liters, the module could include include a procedure to do the conversion. However, in order for this capability to be realized, a dictionary of standard measurement units would need to be developed and included in the framework. Otherwise, module developers would have check all of the possible names for units (e.g. pounds could also denoted by lb and lbs). I think it would be very useful if we did have standard unit names because it would enable modules to work better together with fewer code changes. Otherwise a developer would have to rewrite their code in order to interface with a new module that used different measurement units. How far do you think we should go in handling units?

**Comment by jrawbits** [comment]
I’d suggest that we define a “Units” attribute that is simply text string and encourage developers to fill those in with something reasonable and attainable.

In the module, this attribute would be sought on input files, and attached to output files.  Files that are passed into the module for processing should have a “Units” parameter (and the suggested “Units” for each input element should be defined somehow in the module’s input specification).  The input “Units” are also a string, and we do simple string comparison (if they’re the same, great; if “Units” are missing from the input, we presume they’re correct but warn the user what we’re expecting; if the “Units” do not match, then we exit with an error about Unit mismatch and tell the user what we want, so they can fix either the data itself or the Units string).

We might want to promulgate standard ways of expressing the Units as strings (i.e. a dictionary) and might one day imagine providing functions to perform Unit conversions (essentially listing a “from” string, a “to” string, and what you need to do to convert from one to the other, including possibly an identity function if these are just different string representations of the same actual unit).  But barring an internet resource maintained by a true standards agency (which would probably be prohibitive and likely only available for base physical units, see units(1)<http://www.gnu.org/software/units/> from the GNU project) we’re stuck winging it with strings like “persons per household” or “kilojoules per person”.

**Comment by gregorbj** [comment]
I'm also thinking that units would be represented as strings. I'm not thinking of any other representation. I believe, however, that we need to establish some naming conventions for the units. Otherwise even if we just do a simple match of input and output units names, we will get warnings when there shouldn't be. For example if the output units are stored as 'lbs' and the input is looking for 'lb'. I recognize that it would be a substantial amount of work to develop a comprehensive dictionary of acceptable unit names, but I wonder whether if could be done in a more incremental way. For example, as we convert GreenSTEP/RSPM/EERPAT/RPAT modules to the new framework, we can have an on-line catalog of unit names that we add to as we go. Then whenever a developer wants to add a new module to the system, one of the things that is checked is the unit naming and if the module has new units of measure, these are added to the catalog.

**Comment by jrawbits** [comment]
Naming conventions for the units make perfect sense (as would the slightly harder task of documenting what we have actually used and keeping a list in one place).  Because matching the Units will really only going to be a concern for module and application developers (end users will always be told “you have to provide this data element in these units”), I think they should be expected to consult the documentation for the modules they’re planning to interact with (which should state the “unit string” defining each of the input data elements).  End users will need to read the documentation if they are to have a prayer of getting useful results.

If we have a master database of such strings for the modules we develop along with some basic naming conventions, and keep them up to date, that would be useful to new module developers.  An online catalog would probably be overkill (though we might encourage such a thing to emerge in a future RSPM Wiki).  With respect to who maintains such a thing, you say “one of the things that is checked” but give no clue about the work flow that would direct new contributions to such an agent, nor what their authority would be to accept or reject or ask for something different.

In my previous comment, I suggested a really simple lookup table for “conversions” (especially those that are just “aliases”), and I think that might be the easiest approach.  Such a table could be built incrementally by whoever.

**Comment by bstabler** [comment]
I think a unit attribute as a string is a good idea and is sufficient.  I'd prefer the developer of a module to have to interpret the unit string and decide what to do with it, rather than rely on some sort of unit conversion based on a labeling convention.  I would propose that we start with this and see how we use the unit string, and then see if we need or want to revise it.

**Comment by mrspeel** [comment]
Other units dimensions that should be defined by the module....
- base unit (e.g., lbs)
- temporal unit (e.g., annual, daily)
- totals vs deltas (e.g., RPAT has several outputs that are changes from a base year rather than a total for the given year)
