### ISSUE TITLE
UI allows users to save tables read from the datastore to CSV

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#84]
from ODOT: "We had questions about how the data is stored via rhdf5 format and if its necessary to have all the data vectorized.  It makes reading the synthesized data (in the case of the currently constructed SyntheticFirms module) difficult but realize that with larger study areas this may be necessary."

response: HDF5 is likely here to stay but we'll make it easier to save data to easier-to-use formats.  So, let's add a feature to the UI to allow users to save tables read from the datastore to CSV.

**Comment by bettinardi** [comment]
I think you are missing the issue with this one.  The issue was that instead of tables stored in HDF5, you have endless vectors stored in HDF5 - look at the resulting output in an HDFViewer - it looks really bad and is a mess.  Is there any reason why tables of data can't be stored...

**Comment by bstabler** [comment]
The design of VE is that the user doesn't need to worry about how data is stored within the hdf5 file.  What we can also do is add a visioneval function to read a whole table from the datastore.  I think there is already a functrion to do this, but I don't think it is public right now.  @gregorbj?  This function would wrap reading/writing a dataframe to hdf5.  This is similar to Python pandas' [to_hdf](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_hdf.html) and from_hdf.

**Comment by gregorbj** [comment]
Alex, you can't save tables with different types of data in an HDF5 group. An HDF5 dataset, just as in R has to have one type of data (e.g. numeric, characters). As in R, although you can have a matrix in HDF5, all the data has to have the same type. The tables in the datastore have several types of data, just as in a data frame (which is actually a list where every vector has the same length). A table in the HDF5 is just like a data frame. The problem is not with how data is stored, it is with how the HDFViewers work. They are not set up to view dataframes. Ben is right, what we need to do is add a function that enables users to view some or all of a table.

**Comment by bstabler** [comment]
@PeterVermont suggested we look into [h5table](https://support.hdfgroup.org/HDF5/Tutor/h5table.html) support as well.

**Comment by bstabler** [comment]
@PeterVermont  - we also want to move the display of output tables to an outputs section instead of settings.

**Comment by PeterVermont** [comment]
![image](https://cloud.githubusercontent.com/assets/889233/25920225/46a771ce-359f-11e7-8b8d-e0b6031e7ed0.png)


This is working
